### PR TITLE
fix: implement `EdmFilter.func` decorator to map methods as valid OData expressions

### LINKED ISSUE #257: Use a decorator to identify that a method of `DataFilterResolver` class should be used for OData expressions
It would be very useful to have a decorator e.g.
```javascript
@EdmMapping.filter()
whoami() {
     // write code here to get username and use it in OData expressions like /articles?$filter=author eq whoami()
}
```
and allow `DataFilterResolver` to identity such methods.

Important Note: The usage of method decorators is not supported internally`@themost/data`.  But it can be used outside `@themost/data` module to extend `DataFilterResolver` class. 

For using method decorators internally -for the existing methods of DataFilterResolver- we should use `Object.defineDecorator()` method provided by https://github.com/themost-framework/data/blob/master/odata.js#L2112

### PR DESCRIPTION
**Pull request by phxgg**
~~this fix makes sure the `name` property is directly defined in the `DataFilterResolver` prototype and is not inherited from another object up the chain~~

Implements the `EdmFilter.func` decorator and validates existing methods that are used as OData expressions in  `data-filter-resolver.js`

fixes: #257

### CODE REVIEW

File: data-filter-resolver.js [hunk 1]
```diff
@@ -35,7 +35,7 @@ DataFilterResolver.prototype.resolveMember = function(member, callback) {
 
 DataFilterResolver.prototype.resolveMethod = function(name, args, callback) {
     callback = callback || function() { };
-    if (typeof DataFilterResolver.prototype[name] === 'function') {
+    if (Object.prototype.hasOwnProperty.call(DataFilterResolver.prototype, name) && typeof DataFilterResolver.prototype[name] === 'function') {
```
Comment (kbarbounakis) [inline data-filter-resolver.js]: It seems that we have to exclude some functions e.g. `resolveMethod` or `resolveMember` before executing them and get the result.
